[package]
name = "blip"
version = "0.1.0"
authors = ["jekrb <jake@burden.blog>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = { version = "0.2.17", features = [ "paw" ] }
paw = "1.0.0"